title: Niccolò Urbinati
description: I am a postdoctoral researcher in Mathematical Economics, at the Department of Economics of Ca' Foscari University, Venice.
logo: /assets/img/Fototessera_Venezia.png
theme: jekyll-theme-minimal
